### ISSUE TITLE
Plugin doesn't recognize steps that use `` instead of '' or ""

### ISSUE THREAD

**Issue by onthespotqa** [cucumber/language-service#101]
### 👓 What did you see?

Extension does not recognize steps that use backticks instead of quotes.

### ✅ What did you expect to see?

I would expect the extension to recognize steps that use backticks.

### 🔬 How could we reproduce it?
In a step file create a step that uses backticks

```
When(`I fill:`, () => {
  console.log('filling in')
});
```

**Comment by aslakhellesoy** [comment]
Partial support for template literals (`I fill:`) would be trivial to add. However, string interpolation cannot be supported (`I ${something}`).

This library parses the source code (using the tree-sitter library) to extract the step definition expressions, but it doesn’t *execute* or *interpret* the source code, which would be necessary in order to evaluate string interpolation.

We could recognise template literals without interpolation and process those, and ignore template literals with interpolation.

Are you relying on interpolation at all? And if not, why are you using template literals and not simple single/double quoted strings?

**Comment by xeger** [comment]
Good question! In my project, I'm using template literals because my steps frequently use both `'` (in the grammatical genitive sense) and `"` (to quote multi-word parameters). The backtick is a handy way avoid escaping one or the other. I don't use substitution in my template literals, and naturally I wouldn't expect Cucumber to help if I were too.

Your proposal to handle substitution-free literals would work ideally for me. Trying to account for them would probably just cause confusion.

**Comment by aslakhellesoy** [comment]
@xeger @onthespotqa should be fixed in Cucumber VSCode 1.5.0. If you like it, please give us ⭐⭐⭐⭐⭐ at https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official

❤️

**Comment by xeger** [comment]
Confirmed that it's not working for me, either, with 1.5.0. 🤔 I will review your PR and see if there's an obvious reason.

I lack permission to reopen this issue; will open a new one if I have anything useful to contribute in the way of troubleshooting details.

**Comment by aslakhellesoy** [comment]
I just pushed 1.5.1 where I believe it's fixed. The fix was 001e34f4014499b6ec6a30c529269f1515eec348.

**Comment by aslakhellesoy** [comment]
Now did I earn some ⭐⭐⭐⭐⭐  at [the marketplace](https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official)? 🥺

**Comment by xeger** [comment]
You've earned a lot more than that, my friend, with all of the excellent tooling you've given me over the years!

**Comment by onthespotqa** [comment]
confirmed its fixed. thanks for the quick turnaround.
